name: basic_ecommerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.2+1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-SemiBold.ttf

    - family: Halant
      fonts:
        - asset: assets/fonts/Halant-Medium.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/lightsplashicon.png
  color_dark: "#0C0C0C"
  image_dark: assets/images/darksplashicon.png
  android_12: